


CREATE TABLE users (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY , 
    user_name VARCHAR(255) NOT NULL 
);

CREATE TABLE messages (
id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
author_id INT NOT NULL ,
message VARCHAR(200) NOT NULL,
posted_at TIMESTAMPTZ DEFAULT NOW(),
FOREIGN KEY (author_id) REFERENCES users(id)
);



